### ISSUE TITLE
MMM-Wallpaper requires write permission

### ISSUE THREAD

**Issue by accountnumber3** [kolbyjack/MMM-Wallpaper#10]
It's been a while since I discovered this and I can't test it right now. But when I tried to point at a directory with read only permissions it failed to load any wallpapers. I also tried to mount to a subdirectory and it still failed. It only worked with rw permissions, which I do not want.

**Comment by kolbyjack** [comment]
I think you must be confusing this module with another one, my module loads images from remote sources (bing, reddit, icloud, etc), not a local directory.
