### ISSUE TITLE
Can we resize/reposition vertical images

### ISSUE THREAD

**Issue by mlcampbe** [kolbyjack/MMM-Wallpaper#105]
I've got the iCloud source setup and it works as expected but the photos that are in portrait/vertical orientation are getting cropped in what appears on the top and bottom of the photo.

Ideally the module would resize the photo so that the vertical height matches the display height leaving the left/right sides black. Is there anyway to accomplish this with the current module?

Another option might be to decide to crop at the top or bottom of the photo and display the remainder.

Is that something we could potentially see fixed?

**Comment by kolbyjack** [comment]
You can accomplish this by setting "size": "contain" in the module config

**Comment by mlcampbe** [comment]
Thank you for the quick reply. It works perfectly.
