### ISSUE TITLE
iCloud Photo DNS Error

### ISSUE THREAD

**Issue by zekyl314** [kolbyjack/MMM-Wallpaper#111]
I have recently added this module to my Magic Mirror.  
Unfortunately I am getting the following error, which seems to be on Apple's side.  They must have changed the URLs and I am not certain how you obtained these in the past.  I'd like to correct it and use the module.  Any ideas?

[2024-08-30 11:30:48.410] [ERROR] Whoops! There was an uncaught exception... 
[2024-08-30 11:30:48.417] [ERROR] TypeError: fetch failed
    at node:internal/deps/undici/undici:13179:13
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  [cause]: Error: getaddrinfo ENOTFOUND p682-sharedstreams.icloud.com
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'p682-sharedstreams.icloud.com'
  }
}

**Comment by kolbyjack** [comment]
I think I just loaded the iPhoto website and reverse engineered the requests using the chrome debugging tools, but it's been so long, I can't remember how it really even works.  I don't have the free time I used to, so unfortunately, I don't think I'll be able to address this myself, but would be willing to accept a pull request.

**Comment by zekyl314** [comment]
@kolbyjack oh my, you can close this.  This problem was my fault, I was adding the # in the configuration for the album ID.  I need a cone of shame emoji.  Another user posted an article on the MMM forum on how they got theirs working.  I cannot believe it was that simple as I made a bone head mistake.
 https://forum.magicmirror.builders/topic/14807/mmm-wallpaper-configure-for-icloud-album-photo/3
