### ISSUE TITLE
Feature: Next image trigger form notifications?

### ISSUE THREAD

**Issue by Andoramb** [kolbyjack/MMM-Wallpaper#15]
Hi @kolbyjack, I love the module!

Is it possible to trigger _Next Wallpaper_?
For ex. if I have an array of sources, would it be possible to skip the current image?
like with notifications?

Thanks!

**Comment by kolbyjack** [comment]
You should be able to trigger loading the next image by having another module send a "LOAD_NEXT_WALLPAPER" notification now.

**Comment by Andoramb** [comment]
Yes, and how cool is that 👍
