### ISSUE TITLE
Feature: possible to add dim to top and bottom?

### ISSUE THREAD

**Issue by Andoramb** [kolbyjack/MMM-Wallpaper#16]
Hi again.
I noticed that a lot of wallpapers would look much punchier if there is a dim on top/bottom of the screen, just like on [Wallberry theme](https://github.com/delightedCrow/WallberryTheme#now-with-more-options-for-bright-images) 
Would it be beneficial for the looks to add like 2 overlays with fade to top/bottom?
Thanks! :)

**Comment by kolbyjack** [comment]
I don't really see the fade you're referring to, I assume they're placing a couple of divs over the top and bottom of the image and applying some css to them?

**Comment by Andoramb** [comment]
Exactly :) 2 divs on top/bottom with `linear-gradient` css like here: [WallberryTheme.njk](https://github.com/delightedCrow/WallberryTheme/blob/2859099cca0cfa9d0d0eebd537303d3b59407bb3/WallberryTheme.njk#L7)

**Comment by straubus** [comment]
Could You please help me in adding those parameters to css?
I also want every photo to dim to top/bottom, what should I do?

**Comment by editwentyone** [comment]
i second this, having two gradients top and bottom is visually much better

**Comment by kolbyjack** [comment]
Pull latest and set `fadeEdges: true` in your config.

**Comment by editwentyone** [comment]
thank you, I added this to my `custom.css` to make it softer 

```
.MMM-Wallpaper .top-gradient {
    height:15%;
    background: linear-gradient(rgba(0,0,0,0.5), transparent);
}

.MMM-Wallpaper .bottom-gradient {
    height:15%;
    background: linear-gradient(transparent, rgba(0,0,0,0.5));
}
```
