### ISSUE TITLE
iCloud configuration

### ISSUE THREAD

**Issue by girottov** [kolbyjack/MMM-Wallpaper#17]
Hi, following specs on the documentations I cannot display iCloud pictures. here below my config. Bing works fine but no way to link an iCloud shared photo album.

Thanks to drive me to the appropriate syntax for sourcing images from iCloud.

module: "MMM-Wallpaper",
    			position: "fullscreen_below",
    			config: {
				filter: "grayscale(0.5) brightness(0.5)",	
      				//source: "bing",
				source: "icloud:<https://www.icloud.com/sharedalbum/#B0hGnbeumdKqrW>",
      				slideInterval: 60 * 5000 // Change slides every minute
    				}

**Comment by kolbyjack** [comment]
Try `source: "icloud:B0hGnbeumdKqrW"`

**Comment by girottov** [comment]
Hi, thanks for the quick answer. I did the try but does not work. iCloud URL is fully accessible and not protected by password or authentication (you can even see my photos if you just click on it), therefore I would not expect issues in connection. It is currently in use by Dakboard, and migrate from Dakboard (paid service) to MM (open source) is my current challenge.

Unfortunately I do not have right skills to debug the MM module so far.

**Comment by kolbyjack** [comment]
I just tested it locally, and it worked for me.  Do wallpapers show up for you if you use a different source, like bing?

**Comment by girottov** [comment]
Space between : and B0 was missing. Thanks for your support, issue resolved
