### ISSUE TITLE
Squished images after update

### ISSUE THREAD

**Issue by wesdonohue** [kolbyjack/MMM-Wallpaper#18]
Maybe it's just me, and I've messed something up, but after updating Magic Mirror all of the images are squished down into about a 1 inch thick line running horizontally across the screen. All of my other modules are still working correctly. Maybe something not playing nice with the latest magic mirror update?

**Comment by kolbyjack** [comment]
Which branch are you on?  Can you put your config in here?  I'm running with latest master, and not seeing any issues.

**Comment by wesdonohue** [comment]
It was an issue with another module I was using. I noticed that that module
wasn't working, removed it from my config to test, and the image was fixed
when I started mm back up. I wish I could remember which module it was, but
it wasn't anything I really needed so I just deleted it and all is working
now.
