### ISSUE TITLE
Filter NSFW-tagged images

### ISSUE THREAD

**Issue by MikeBishop** [kolbyjack/MMM-Wallpaper#20]
I would love to add [r/ITookAPicture](https://www.reddit.com/r/ITookAPicture/) to my wallpaper rotation, except for one problem....  Not every picture on that subreddit is suitable for display to my wife and kindergartner.  ([This](https://www.reddit.com/r/itookapicture/comments/ix5ypo/itap_of_my_lady_love_mlm/), for example, is lovely but not really what I want displayed in my kitchen.)

Would it be possible to have an option to filter out any posts tagged NSFW?  This does appear to be in the JSON as `"over_18": true`, so it's a simple addition for Reddit at least; I can't speak to the other sources.

**Comment by kolbyjack** [comment]
Try current master, I've added a nsfw boolean config option (default
true).  Just set it to false, and it should filter out over_18 posts.
