### ISSUE TITLE
iCloud low quality and no crossfade

### ISSUE THREAD

**Issue by radimkarnis** [kolbyjack/MMM-Wallpaper#22]
Hello @kolbyjack , thank you for your amazing work on this module. 
I have an issue with loading pictures from iCloud album - sometimes the picture loads in full resolution and sometimes horribly downscaled, what could be the issue?

Also, I get no crossfade even though I set it in the config file accordingly:

```
{
module: "MMM-Wallpaper",
position: "fullscreen_below",
config: {
source: "icloud:XXXXXXXX", // Hidden for privacy
slideInterval: 15 * 1000, // Change slides every 15 sec
updateInterval: 60 * 60 * 1000,
maximumEntries: 300,
crossfade: true
}
},
```

Thank you for your time and help.

**Comment by kolbyjack** [comment]
I haven't actually used the iCloud mode since it was added, I can't even remember how to find the album id, can you refresh my memory, so I can try to debug this?

**Comment by radimkarnis** [comment]
Thank you for your answer! I just looked at the URL of the shared album and took the ID from there, it is the part aftert the # sign. You can debug with my album ID: B0L532ODWGuFLqC if you don´t mind seeing my cheesy pictures.

**Comment by kolbyjack** [comment]
Ok, I've pushed some changes that should fix up the crossfade and resolution issues, let me know if you encounter any more issues.

**Comment by radimkarnis** [comment]
Thank you @kolbyjack , that solved both of my issues. Awesome work!
