### ISSUE TITLE
Possible to do not fullscreen?

### ISSUE THREAD

**Issue by datamunk** [kolbyjack/MMM-Wallpaper#24]
Hey kolbyjack. Really loving the wallpaper module. I've got it all set up using icloud and it works perfect. However, I'm thinking I actually want to have my photos be much smaller, only because I'm having issues with sometimes reading text. I'm honestly wanting to use some CSS to put them within a "polaroid" looking border thats rotated, off center using the code below (snagged from another github for a diff photo module). However, yours is the best (and only) I can find that utilizes iCloud for showing photos

I'll be the first to admit I'm not the greatest at coding, though I can generally troubleshoot or slog my way thru some stuff. I'm not sure where to start with my goal, though. I've changed position on your config to say upper_third, but then its on top of everything. If I add _below, then its just black (no error config screen tho).

Any tips on how I can push the photos using your module to something other than fullscreen?  

I've tried using the code below and it doesnt do anything, not sure if it is calling some code from the original module (MMM-Instagram)

Another thing I had considered was setting up a cronjob to actually use that instagram module and download files automatically, but I was trying to avoid so as to not fill up my memory card on the rpi 4

#MMM-Wallpaper-image {
    box-shadow: 10px 10px 15px #aaa;
	padding: 10px 10px 30px 10px;
	border: 1px solid #bfbfbf;
	background-color: #fff;
	transform: rotate(-6deg);
	-ms-transform: rotate(-6deg);
	-webkit-transform: rotate(-6deg);
}

**Comment by kolbyjack** [comment]
If your photos are making the text unreadable, you could try changing the filter config.  I actually have mine set to `grayscale(0.5) brightness(0.3)`, which is a little darker than the default, and makes everything a little more readable.

As for shrinking the image and adding a polaroid-like border, that may be possible, you could try editing MMM-Wallpaper.css like so:

```
.MMM-Wallpaper .wallpaper {
  position: fixed;
  left: 50%;
  top: 50%;
  transform: translateX(-50%) translateY(-50%) rotate(-6deg);
  box-shadow: 10px 10px 15px #aaa;
  padding: 10px 10px 30px 10px;
  border: 1px solid #bfbfbf;
  background-color: #fff;
}

.MMM-Wallpaper .tall {
  width: 30%;
}

.MMM-Wallpaper .wide {
  height: 30%;
}
```

You can try playing with the .wide and .tall values to adjust the size of the images, and the left and top values of .wallpaper can move the image to where you want it on the screen.

**Comment by datamunk** [comment]
Thanks, going to give it a shot now! Appreciate you taking the time to send
that!

**Comment by datamunk** [comment]
Man! It works, and absolutely PERFECTLY! THANK YOU!

**Comment by datamunk** [comment]
Hey @kolbyjack. Just curious, still loving the tweak ya gave me. I'm wondering, is there a way to change the width and height % depending on if the photo is portrait or landscape? The settings I have are 50% for both and I changed the top to 35% and its great for portrait, Landscape photos it shrinks down pretty small to fit the same width. Could honestly probably grow by to like 50% for width or something

**Comment by kolbyjack** [comment]
The .MMM-Wallpaper .tall style should take effect for portrait photos, and .MMM-Wallpaper .wide should take effect for landscape.
