### ISSUE TITLE
URL help

### ISSUE THREAD

**Issue by RMRit** [kolbyjack/MMM-Wallpaper#25]
Super new to this... I am trying to view a Adobe Lightroom Portfolio, do I just paste the URL to my shared album? I am getting a black screen. If paste individual photo links it works fine but It doesn't cycle images

			module: "MMM-Wallpaper",
			position: "fullscreen_below",
			config: {
                                       source:"https://ryanritchie.myportfolio.com/gallery",

**Comment by kolbyjack** [comment]
Right now, the module doesn't support extracting images from a page like
that.  Let me take a look and see how difficult it would be to add support
for it.

**Comment by kolbyjack** [comment]
Try updating and setting your source to `"lightroom:ryanritchie.myportfolio.com/gallery"`

**Comment by RMRit** [comment]
No luck it pulls from what appears to be a default Bing, a harbor and dragonfly. I’ve used both the share Link feature in Lightroom as well as the published web portfolio.

**Comment by RMRit** [comment]
Thank you! Works beautifully! Now I just need to remove the vertical images from my gallery, unless I am missing a way to make them fit.

**Comment by kolbyjack** [comment]
Ok, I've now added a `size` config option, try updating again and setting `size: "contain"` in your config, I think that's what you want.

**Comment by RMRit** [comment]
Perfectly executed thank you!
