### ISSUE TITLE
Possible to local images?

### ISSUE THREAD

**Issue by openedhardware** [kolbyjack/MMM-Wallpaper#27]
Is it possible to indicate a local directory path so that the images are displayed randomly? or sequentially?

**Comment by kolbyjack** [comment]
Try latest master, you can set your source to `"local:/path/to/directory"` and it will read the images in that directory.  Be aware that it doesn't recurse into subdirectories.

**Comment by openedhardware** [comment]
Perfect! Will give it a try soon!
