### ISSUE TITLE
Flickr group photos not displaying

### ISSUE THREAD

**Issue by BillyTheKid9588** [kolbyjack/MMM-Wallpaper#28]
Hi,

I have tried to use your module with flickr group 42097308@N00, however it does not work correctly.

The api string is built correctly and the image owner is displayed in the bottom right of the screen, however the image does not load correctly.

Are you able to check on your side?

Thanks for the great module!

**Comment by kolbyjack** [comment]
This was happening because the flickr handler was attempting to load the high-res versions of the images returned by the api.  That worked for my testing, but it doesn't appear to work for your group.  I've added a `flickrHighRes` option, set that to false in your config and it will work.
