### ISSUE TITLE
Flickr, Reddit, Chromecast sources not respecting orientation

### ISSUE THREAD

**Issue by BillyTheKid9588** [kolbyjack/MMM-Wallpaper#29]
I use my dashboard in portrait mode so only want to pull back portrait photos. None of the sources seem to respect the orientation mode.

Does this option work? Does it only work for some sources?

Thanks

**Comment by kolbyjack** [comment]
Yeah, that's really only supported by the Bing source, because Bing explicitly provides landscape and portrait versions of each daily wallpaper.
