### ISSUE TITLE
Local Pictures not resizing when cover is selected

### ISSUE THREAD

**Issue by illbill4rill** [kolbyjack/MMM-Wallpaper#31]
pretty much what it says in the title, the pictures will resize during transitions, but afterwards it seems to switch to contain

**Comment by roo82** [comment]
I'm seeing this as well, but with any parameter passed to size, i.e. cover, contain, or auto. It also happens whether crossfade is set to true or false. 

Here's my module config, if it's useful:

{
                        module: "MMM-Wallpaper",`
                        position: "fullscreen_below",
                        config: { // See "Configuration options" for more information.
                                source: "local:/mnt/nfs/...snip.../",
                                size: "cover",
                                slideInterval: 30 * 1000 // Change slides every minute
                        }
                },

**Comment by mentario** [comment]
Hi there, 

i really like this module, but im experiencing a similar misbehaviour.
On the first cycle, alle images are shown perfectly sized.
After the first cycle, pictures are no longer sized on time, BUT they are sized to monitorsize while being show.
Its always missing a part on the right side. ( I can see the previous image behind it ).
a fix would be SO lovely :)

**Comment by openedhardware** [comment]
Same issue on my RPi 4...

![image](https://user-images.githubusercontent.com/16890683/122548216-a4ca6780-d063-11eb-9cf7-c601029e6595.png)

You can see that the next image is not resized correctly.

This happens sometimes.

How can we fix this issue?

**Comment by kolbyjack** [comment]
Can you try the dom-refactor branch?  It removes the elements from the normal module hierarchy, which should mean that I can control the size better.

**Comment by openedhardware** [comment]
Hi, @kolbyjack 
Yeah, `dom-refactor` branch doesn't have that issue! :+1: 

By the way, is there any tip to improve the performance on 4K display?
The image transition is very choppy and the current second of the time module stops increasing for 2~3s.

Thanks!

**Comment by kolbyjack** [comment]
You could try setting crossfade: false in the config, that usually helps some.  Closing this ticket for now since the reported issue appears to be resolved
