### ISSUE TITLE
Web Locations

### ISSUE THREAD

**Issue by CraigTorg** [kolbyjack/MMM-Wallpaper#33]
I am sure it is something simple. The Bing, Fire TV, and Chromecast sources all work great but I cannot figure out how to pull images from any of the other sources. I am pretty sure that I have the source section placed correctly in the config because I can switch between Bing, Fire TV, and Chromecast.

I am using the Magic Mirror OS which places the modules folder under a "mounts" folder. I can't imagine that would make a difference.

Any idea what I might be doing wrong?

**Comment by CraigTorg** [comment]
I have discovered that the photo file names (I am trying to pull from a Flickr group) are showing up and rotating in the lower right corner of the Magic Mirror screen. It is a really small title in the lower right. Seems like the correct photos and also pulling the correct amount of max entries but there are still no photos being shown.

**Comment by kolbyjack** [comment]
Some flickr albums don't provide high res versions of the images, can you try setting `flickrHighRes: false`?

**Comment by CraigTorg** [comment]
That was it! I had tried calling it true thinking that the files might be too big; overwhelming the RPi. This is great! Thanks!

**Comment by CraigTorg** [comment]
So...I lied. I thought that worked but it looks like it just defaulted back to the Bing list :/

**Comment by kolbyjack** [comment]
Can you paste the module config in a comment here, just block out your actual group id with xxxx or whatever

**Comment by CraigTorg** [comment]
{
                        module: "MMM-Wallpaper",
                        position: "fullscreen_below",
                        config: { // See "Configuration options" for more information.
                                slideInterval: 60 * 1000, // Change slides every minute
                                source:"flickr-group:78115702@N00", 
                                flickrHighRes: "false",
                                maximumEntries: '3'
                        }
                },

I am trying to pull from a general group just to get it working. I would like to eventually be able to have a shared location where my wife and I could easily update photos to update the wallpaper with family photos or something.

Thanks for your help!

**Comment by kolbyjack** [comment]
ah, javascript is terrible when it comes to this.  `"false"` is a truthy value, because it's a non-empty string.  That needs to just be `flickrHighRes: false`

**Comment by CraigTorg** [comment]
Still nothing. I grabbed the "else if" url from the node_helper.js file and manually subbed out the group name (not in the file but copy and pasted in a web browser). It is pulling the Flickr api so I am not sure why it won't get images for my background. Any chance that it may take loading time? Does it have to go through the whole group of photos before it randomly generates the max entries?

**Comment by kolbyjack** [comment]
Are you restarting the server after making the config changes?  It caches the image list for 90% of the updateInterval, so it may have the high res urls cached if you're not restarting it.  I tested locally with the config you pasted and it worked just fine, I loaded a few low-res images of snowy hills, it looked like?

**Comment by CraigTorg** [comment]
Ah...not the whole server. Just refreshing the screen. I'll give that a go. Good to know it is working on your end. Would you mind sharing your module config code?

**Comment by CraigTorg** [comment]
Got it for real this time! Awesome! Thanks!

**Comment by CraigTorg** [comment]
I have a Flickr question. I am only able to get photos from groups if flickrHighRes is false. Is there a way to pull high res photos? I tried uploading my own photo to a new group. I can use it as a wallpaper but only in low res. I know the photo is high res and has a high res file on Flickr. Do I need to add a tag at the end of the group id to force a pull of higher resolution photos?

**Comment by kolbyjack** [comment]
It appears that flickr changed their api since I first wrote the module, their high res pictures now get a separate hash from the low res versions.  I'll see if I can change the method I use to extract the photos to parse their html instead

**Comment by CraigTorg** [comment]
Gotcha. Thanks for taking a look at that!
