### ISSUE TITLE
icloud photos not working

### ISSUE THREAD

**Issue by jbabek** [kolbyjack/MMM-Wallpaper#34]
Great module...but can't seem to get icloud photos to work.  This is how I read the docs, but it doesn't seem to work.  

source:  "icloud: www.icloud.com/sharedalbum/#1234abcd" 

Can you post an example of the source line?  Thanks in advance.

**Comment by kolbyjack** [comment]
It should just be source: "icloud:1234abcd"

**Comment by jbabek** [comment]
Worked like a charm...thank you for the excellent module and support.
