### ISSUE TITLE
Synology Moments issue

### ISSUE THREAD

**Issue by Dwyerave** [kolbyjack/MMM-Wallpaper#35]
I am not able to use the synology moments configuration. I type in source: "synology-moments:<url>" into config file. I replace <url> with the url that synology moment created for the album.   Any help would be greatly appreciated.

**Comment by kolbyjack** [comment]
This really isn't much to go on, does it display anything?

**Comment by Dwyerave** [comment]
Thank you for the quick response.  See below for what I entered into the config file.

		{
    module: "MMM-Wallpaper",
    position: "fullscreen_below",
    config: { // See "Configuration options" for more information.
      source: "synology-moments: https://<URL from Synology Moments was removed for privacy>",
      slideInterval: 60 * 1000 // Change slides every minute
    }
  },

When I run Magic Mirror it just shows a blank screen no matter how long I leave the program running.

ANy help would be greatly appreciated.

**Comment by kolbyjack** [comment]
I'm not sure if this would cause it, but can you try removing the space between `synology-moments:` and `https://`?  I don't trim the result, so I wonder if that leading space is throwing something off.

**Comment by kolbyjack** [comment]
Can you try again with latest master?  It trims what it can, which may fix your issue.
