### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by bytecanarias** [kolbyjack/MMM-Wallpaper#36]
I only have the time, weather and compliments modules and no images load.

**Comment by alexey-gamov** [comment]
Same thing - trying to detect what a mess.
For now only `docker container restart mm` helps

**Comment by kolbyjack** [comment]
Can you post your config?

**Comment by sabres7th** [comment]
Would it be possible to get an example configuration for just a normal image hosted on the local directory for the background I'm not exactly sure if I should use the sideways triangles or not one referencing the directory I just want a normal picture can I please see someone's configuration to copy it

**Comment by sabres7th** [comment]
???

**Comment by alexey-gamov** [comment]
> Would it be possible to get an example configuration for just a normal image hosted on the local directory for the background I'm not exactly sure if I should use the sideways triangles or not one referencing the directory I just want a normal picture can I please see someone's configuration to copy it

```
{
	module: "MMM-Wallpaper",
	disabled: true,
	position: "fullscreen_below",
	config: {
		source: "local:css/backgrounds",
		crossfade: true,
		slideInterval: 180 * 1000,
		filter: "grayscale(0.3) brightness(0.55)"
	}
}
```

**Comment by Priwin1** [comment]
Maybe i can get some help from you.  I try to use a shared i cloud Album as the source for the wallpaper, but the screen stays black. The shared Album is only a test Version, so feel free to try it with this one.
Thanks for your help.
<img width="551" alt="WALLPAPER help" src="https://user-images.githubusercontent.com/87654296/126167824-8784c353-3bff-42e8-89f2-0955ab1f2565.png">

**Comment by kolbyjack** [comment]
You only need the album id, so `icloud:B0IGY8gBYGePzhS`

**Comment by Priwin1** [comment]
Thank you

 

 

Von: Jon Kolb ***@***.***> 
Gesendet: Montag, 19. Juli 2021 15:48
An: kolbyjack/MMM-Wallpaper ***@***.***>
Cc: Priwin1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [kolbyjack/MMM-Wallpaper] Black screen (#36)

 

You only need the album id, so icloud:B0IGY8gBYGePzhS
