### ISSUE TITLE
icloud photos stop changing/ updating

### ISSUE THREAD

**Issue by sluggg** [kolbyjack/MMM-Wallpaper#42]
Thanks for your help yesterday getting icloud photos working. 
Unfortunately I face another issue. 
The photos work and load fine changing every min and then after a period of time the photos stop changing and remain stuck on a single image until I close and reopen the mirror software or force reload?
Thanks again for all help

**Comment by kolbyjack** [comment]
I switched my source to an iCloud album and let it run all day, it never stopped.  Does it always stop on the same image?  How large are your images?  I know some people had similar issues a while back with large images from /r/earthporn, they were running out of memory, iirc.

**Comment by geekqq** [comment]
I have the same issue, it stopped changing at the different image, then I will have to restart the magic mirror so it went back to normal. all the images where take with my iPhone, so they are probably around 5 or 6 MB?

**Comment by kolbyjack** [comment]
Are you able to look at the console output from the browser, or the log output of the magicmirror server?  Without being able to reproduce it locally, I can't tell what's going wrong.

**Comment by geekqq** [comment]
Sorry I am not a tech guy, can you be more specific on how to check the console output from the browser please? Thanks

**Comment by kolbyjack** [comment]
In chrome:
  - Press ctrl+shift+j to bring up the developer console
  - Switch to the Network tab so it will record requests
  - Wait for requests to fail
  - See if there are requests that are now failing to complete
  - Switch to the console tab to see if there are error messages

**Comment by geekqq** [comment]
Finally I figured it out: I have to use _npm start server_ to go into server mode, then I can use browser to see the mirror by going to localhost:8080
I am waiting for error to come up so I can send you the error message, thanks

**Comment by geekqq** [comment]
It got stuck again this morning. There is no error message in the console though. See the attached screen:
![photo_2021-09-23_11-38-49](https://user-images.githubusercontent.com/53326015/134565061-a57c1255-7455-4c31-97b3-9950aaa8a270.jpg)
![photo_2021-09-23_11-38-46](https://user-images.githubusercontent.com/53326015/134565079-5df8fbcb-898f-4cac-925e-9e0555ba76a8.jpg)

**Comment by kolbyjack** [comment]
If you switch to the network tab (click the >> to show it), does it show any failed requests?

**Comment by geekqq** [comment]
No I did not see any failed requests for wallpaper
![12231](https://user-images.githubusercontent.com/53326015/134585637-49d2b597-3b19-46d6-b0e4-c5aedad9e19c.jpg)

**Comment by kolbyjack** [comment]
Are there any errors in the terminal where you ran `npm start server`?

**Comment by geekqq** [comment]
[24.09.2021 03:47.36.474] [ERROR] Failed to fetch git data for MMM-Wallpaper: Error: fatal: unable to access 'https://github.com/kolbyjack/MMM-Wallpaper.git/': Could not resolve host: github.com

**Comment by kolbyjack** [comment]
If DNS has stopped working, it would make sense that the wallpapers stop loading

**Comment by geekqq** [comment]
Any suggestions on how to solve the DNS problem?

**Comment by kolbyjack** [comment]
That's a system issue, unfortunately, I really don't have any suggestions

**Comment by kolbyjack** [comment]
Give latest a try, I think this should be fixed now

**Comment by geekqq** [comment]
It worked perfectly. Thanks


stonehoo
