### ISSUE TITLE
Flickr group issue / conflict with other module

### ISSUE THREAD

**Issue by bkosk** [kolbyjack/MMM-Wallpaper#44]
I'm having two separate issues: one more with your module, the other may be out of bounds.

First, I'm unable to load Flickr group photos (https://www.flickr.com/groups/1059982@N21/pool/). My config code is:
`module: "MMM-Wallpaper",
psoition: "fullscreen_below",
config: {
source: "flickr-group:1059982@N21",
slideInterval: 10*60*1000
}`
All I get is a black background. If I change the source to "bing" images load just fine.

The second issue is when I also load MMM-NetworkConnection (https://github.com/slametps/MMM-NetworkConnection): it seems to override MMM-Wallpaper. I only get a black screen (no matter the source). When I comment out NetworkConnection module Wallpaper works. I'm just not smart enough to look at each of your sources to determine where the conflict is.
Thank you in advance, and thanks for developing and sharing your work!

**Comment by kolbyjack** [comment]
For the flickr issue, you probably need to set `flickrHighRes: false` in your config.  Some time ago, they changed the way they generate the high-res urls, and I've never gotten around to figuring out how to fetch them now.

I really don't know how MMM-NetworkConnection could be interfering.  Does it show when you enable it, or is the screen completely black?  Perhaps it's an issue with an invalid config when you have them both?

**Comment by bkosk** [comment]
Thanks for the quick reply. Turning off high-res worked! Thank you!

As for NetworkConnection: when I enable it and yours, no wallpapers load. It's just a black background, but all other modules work and show properly.

**Comment by kolbyjack** [comment]
MMM-NetworkConnection depends on speedtest-net, which is patching the core node.js https.request method, and something about its patching isn't playing nicely with MMM-Wallpaper.

**Comment by kolbyjack** [comment]
It looks like https://github.com/ddsol/speedtest.net doesn't depend on agent-base anymore, and agent-base doesn't even monkeypatch https.request anymore, so I think this is a bug for MMM-NetworkConnection to update their speedtest-net version

**Comment by bkosk** [comment]
Okay - I see. Thank you for your help!

**Comment by kolbyjack** [comment]
I added a package.json with a dependency on the request module, try updating to latest (you'll have to run `npm install` in the module directory now) and it should work with MMM-NetworkConnection now.
