### ISSUE TITLE
iCloud Photo Not Displaying

### ISSUE THREAD

**Issue by JEHIVES** [kolbyjack/MMM-Wallpaper#45]
Good evening!  I have been trying to configure this module to work with my public iCloud Photos album for a few days now (off and on).  I have not been successful in getting the source to work for it.  When I use Bing or Chromecast as the source, it works great!

This is likely user error, but I would greatly appreciate any help you are able to provide! 

I've tried the following for the source line:
source: "icloud:https://www.icloud.com/sharedalbum/<assigned#>" - This give me a black screen
source: "https://www.icloud.com/sharedalbum/<assigned#>" - This give me a black screen
source: "icloudphoto:https://www.icloud.com/sharedalbum/<assigned#>" - This defaults back to bing
source: "icloudphotos:https://www.icloud.com/sharedalbum/<assigned#>" - This defaults back to bing

Entire Module for reference:
modules: [
		{//https://github.com/kolbyjack/MMM-Wallpaper
			module: "MMM-Wallpaper",
			position: "fullscreen_below",
			config: {
			  source: "icloud:https://www.icloud.com/sharedalbum/<assigned#>",
			  filter: "grayscale(0.5) brightness(0.5)",
			  orientation: "auto",
			  crossfade: true,
			  updateInterval: 60 * 60 * 1000,
			  slideInterval: 5 * 60 * 1000 // Change slides every minute
			}
		},

**Comment by kolbyjack** [comment]
It should be just be `icloud:<assigned#>`

**Comment by JEHIVES** [comment]
That worked! Just for reference, the iCloud link had a # sign starting that specific code.  I tried it with the # sign and it dit not work.  I removed it and it did!  This just made my weekend!  Thanks!

**Comment by geekqq** [comment]
Where can I get the Assigned ID please? I can not find it anywhere. Thanks

**Comment by geekqq** [comment]
I got it. Thanks

**Comment by vatonerd** [comment]
For assigned ID, you have to use a Mac device and open Photos. There you can identify the shared folder and the ID will be embedded on the URL when you view the shared album on a browser. The ID is the number following the # symbol.
