### ISSUE TITLE
The Wallpaper is shown twice

### ISSUE THREAD

**Issue by MacG-DD** [kolbyjack/MMM-Wallpaper#46]
If I set `position: "fullscreen_below"` at the config.js then the modul is shown twice. One at all at the bottom (at the top of the DIV list) and the second time inside the fullscreen region.

I didn't notice this in operation, I found it in the page source code of the MagicMirror. So it shows the background twice. This should lead to more memory usage.

A quick work-a-round - don't use the position line.

**Comment by kolbyjack** [comment]
The wallpaper isn't actually shown twice.  If you look at the div inside the fullscreen region, it only has an empty span inside.  I've removed position from the example config to avoid the confusion.

**Comment by kolbyjack** [comment]
I originally did use the regions, and there were weird sizing issues _sometimes_, which made them hard to reproduce/debug
