### ISSUE TITLE
problem with MMM pages

### ISSUE THREAD

**Issue by chassain** [kolbyjack/MMM-Wallpaper#47]
Hello,

since a git pull i have always the wallpaper on all pages with MMM-pages. For example : `[ "MMM-Widget41" ],
				[ "MMM-Wallpaper" ,  "MMM-EmbedYoutube" , 'MMM-GooglePhotos' , 'MMM-CoinRanking' ,  "MMM-Widget12" , "MMM-FranceInfo" , "clock"  ],
				[ "MMM-Wallpaper" , "MMM-EmbedYoutube" , 'MMM-GooglePhotos' , "MMM-OnThisDay" , "MMM-FranceInfo" , "clock"  , "MMM-PiTemp" ],`. My magicmirror shoud'nt display wallpaper with Widget 41 like old version of your module.

**Comment by chassain** [comment]
? why closed my problem ?

**Comment by kolbyjack** [comment]
I closed with a commit that puts the module back in the normal module hierarchy.  Try latest master, it should work like you want.

**Comment by chassain** [comment]
perfect. thanks
