### ISSUE TITLE
local images not showing

### ISSUE THREAD

**Issue by geekqq** [kolbyjack/MMM-Wallpaper#48]
So I put my images in the following directory
home/pi/Pictures/Joy, and use the following code:
source: "local:</home/pi/Pictures/Joy>"
but the image was not showing at all.
The images were all JPG format.
Is there anything wrong? 
Thanks

**Comment by kolbyjack** [comment]
You shouldn't actually include <> characters in the source.  Use `source: "local:/home/pi/Pictures/Joy"`

**Comment by geekqq** [comment]
Awesome, thanks for your help. Worked now.
