### ISSUE TITLE
Flickr Groups not showing up

### ISSUE THREAD

**Issue by monukoshy** [kolbyjack/MMM-Wallpaper#51]
I am unable to get flickr groups to show up on magic mirror using the MMM-Wallpaper module.
Please check my code snippet.. not sure why it would not work.

`                {
                        module: "MMM-Wallpaper",
                        position: "fullscreen_below",
                        config: { // See "Configuration options" for more information.
                        source: "flickr-group:113291043@N05",
                        maximumEntries: 50,
                        slideInterval: 60 * 1000 // Change slides every minute
                                }
                },`

**Comment by monukoshy** [comment]
Hi, thanks for stepping in. Yes it did work. But the images are low res. I think they are more like thumbnail images that are fully blurry and pixel torn on the monitor.
Setting it back to true will turn off the flickr source.

**Comment by kolbyjack** [comment]
Ok, it took a while, but I've integrated the flickr sdk to enable loading high-res photos from flickr.  Can you try out the `flickr-api` branch and see if it works for you?  The configuration is a bit different now (though I believe it's clearer and easier), so don't hesitate to reach out if you need help.
