### ISSUE TITLE
Local wallpaper can't display

### ISSUE THREAD

**Issue by smyepp** [kolbyjack/MMM-Wallpaper#52]
I have copied my wallpapers to NAS, the path as follows: //192.168.6.10/wallpaper. Then I edit the config: 
modules: [
                               {
                                              module: "MMM-Wallpaper",
                                              position: "fullscreen_below",
                                              config: { // See "Configuration options" for more information.
                                              source: "local:/192.168.6.10/wallpaper",
                                              slideInterval: 20 * 1000 // Change slides every minute

But it not works, What i am missing?

**Comment by elgeorgie** [comment]
I had a similar issue. Try making the source a directory. add "/" at the end.

source: "local:/192.168.6.10/wallpaper/",

**Comment by smyepp** [comment]
I'm sure  the network path is mounted, I can access the path in rpi directly. Is the source I edited right?   
source: "local:/192.168.6.10/wallpaper"

**Comment by elgeorgie** [comment]
If it's mounted locally, it should have a local path e.g, "/home/pi/wallpaper" instead of the ip

**Comment by smyepp** [comment]
I got it . Thanks alot
