### ISSUE TITLE
Reddit Source no longer working

### ISSUE THREAD

**Issue by EvanHerman** [kolbyjack/MMM-Wallpaper#53]
I am trying to display images from a reddit source, but they don't actually ever get pulled in. Here is the basic config file:

```js
{
	module: 'MMM-Wallpaper',
	position: 'fullscreen_below',
	config: {
		source: "/r/cityporn",
		crossfade: false,
		slideInterval: 3 * 60 * 1000
	}
},
```

I've followed the documentation but it doesn't look like any images ever get pulled in. Any advice would be great. Thanks!

**Comment by kolbyjack** [comment]
I just tried locally with this exact config, and it worked just fine.  Do you see any errors in your browser console or in the terminal where the magicmirror server is running?
