### ISSUE TITLE
Hide source and resolution overlay from bottom right

### ISSUE THREAD

**Issue by cruzanhtpc** [kolbyjack/MMM-Wallpaper#56]
Great work on this module. I am using Reddit  /r/EarthPorn and love it!  what file can i modify to remove the source name and resolution that appear on the bottom right of all the images on screen?  Also Do i need to tell the module maximumEntries  XXX number if i want it to just continuously just keep loading images with no max? i have Shuffle set to true. thank you!

**Comment by kolbyjack** [comment]
Displaying the post title is controlled by the `caption` config item.  I didn't realize I hadn't documented it, but it's [there now](https://github.com/kolbyjack/MMM-Wallpaper#configuration-options).  `maximumEntries` is also set to `10` if you don't set it, and it always needs some value, so you can try just setting it to something large like `100`.
