### ISSUE TITLE
Wallpapers stop updating

### ISSUE THREAD

**Issue by r4zi3lrrr** [kolbyjack/MMM-Wallpaper#58]
Hi,

Has anyone had the issue where wallpapers stop changing on there Magic Mirror?

Getting my feed from Chromecast,  seems to change and work as expected for a bit and then all together stops changing - and stays on one static wallpaper.

**Comment by kolbyjack** [comment]
I've never been able to reproduce this behavior myself, but it sounds like maybe you're having the same issue as #42.  Can you try to follow the instructions in that thread and see if you have any failing requests?

**Comment by PLinz93** [comment]
I have the same issue but only on the target not in the webserver. Can someone help to solve this problem?

**Comment by wsc96** [comment]
I've experienced this too and think it is related to network hiccups (temporary wifi or Internet connection dropouts and in #42 perhaps temporary name resolution issues). I find if the network drops out, even after thet network recovers then the images fail to update. Could be MM not handling the network hiccup or the Wallpaper module (I only run the wallpaper module) but it seems to die and not recover.

I'd like to test with an Ethernet connection but i'm not in a position to do that at the moment.

**Comment by kolbyjack** [comment]
Can you try latest master?  I've made a change to use setInterval instead of setTimeout for the image load timer, at the very least, that should retry each `slideInterval` to load the next image, and shouldn't get stuck.

**Comment by r4zi3lrrr** [comment]
Sorry but how?

**Comment by kolbyjack** [comment]
```
cd ~/MagicMirror/modules/MMM-Wallpaper
git pull
```

**Comment by wsc96** [comment]
I've updated and i'll keep an eye on it :)

**Comment by wsc96** [comment]
Might be worse... it's hung already. Anything you'd like me to grab whilst it is hung?

**Comment by kolbyjack** [comment]
Ok, pull latest again, I think I've finally figured it out.

**Comment by wsc96** [comment]
I've updated... see how we go :)

**Comment by r4zi3lrrr** [comment]
Thank you, will try  updating today. 

⁣Get BlueMail for Android ​

**Comment by PLinz93** [comment]
I have updated it. I will monitor it and let you know.

**Comment by kolbyjack** [comment]
Since you were all very prompt in reporting failures, I'll assume that this is fixed

**Comment by wsc96** [comment]
Haha no issues here so far 👍🏼

**Comment by PLinz93** [comment]
It is solved.

**Comment by r4zi3lrrr** [comment]
Looking good, thanks for resolving the issue. Really good module to have running.
