### ISSUE TITLE
No Wallpaper after Update to Version 2.18

### ISSUE THREAD

**Issue by Der-Gelle** [kolbyjack/MMM-Wallpaper#59]
After updating to version 2.18, the background image of my IP cam is no longer displayed on the Raspberry.

When I access remotely via http://raspberry.pi:8080 the background image is displayed without problems and updated every 10 seconds.

		{
			"module": "MMM-Wallpaper",
			"position": "fullscreen_below",
			"config": { // See "Configuration options" for more information.
				"source": "http://192.168.1.41/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=wuuPhkmUCeI9WG7C&user=admin&password=XXXXXX",
                "slideInterval": 1 * 10 * 1000,
				"updateInterval": 1 * 10 * 1000,
				//"filter": "none",
	            "size": "auto"
					}
		},

anyone have an idea?

regards
Gelle

**Comment by kolbyjack** [comment]
Is this still an issue for you?  If so, can you bring up the developer console on your mirror and see if there are any errors?
