### ISSUE TITLE
nixplay support

### ISSUE THREAD

**Issue by Taylorben159** [kolbyjack/MMM-Wallpaper#63]
I am trying to link my Nixplay playlist to my MagicMirror.  I already have MMM-Wallpaper pulling from a local source and it works fantastic, but my family all got NixPlay frames for Christmas and are sharing playlists and things to each other's frames.  Instead of having a Nixplay picture frame sitting on a wall doing the exact same thing that my MagicMirror is, I thought that I might be able to have your wallpaper module access my pictures from my Nixplay online account.

When I add the line 'source:  "nixplay:app.nixplay.com/#/playlists/playlist/removed for privacy",' I get a rotating wallpaper but it has none of my playlist pictures (they must be stock pictures from NixPlay) **and** it will not pull any pictures from my local storage anymore.  

If I change the line to 'source:  "http://app.nixplay.com/#/playlists/playlist/removed for privacy",' the magic mirror will load, but I get only a black background with no pictures being projected as a wallpaper from either my playlist or my local storage.

I guess I have three questions with this.  
One, any ideas on what I need to change on my source line to be able to pull my actual pictures off of NixPlay?
Two, do I need to have my login information setup in the config to pull my pictures instead of the stock pictures, and if so, how would I add that to my config?
Three, how do I have your module pull from both sources either randomly or in an alternating fashion?

Thank you so much for your help and time with this.  I have been loving learning programming my MagicMirror and figuring out how things are supposed to be formatted to get it to work correctly.

**Comment by kolbyjack** [comment]
nixplay isn't a supported source, they don't appear to have a public api, and I don't have an account to try to add support for it.  When you set your source to `nixplay:whatever`, the module is falling back to displaying bing's daily wallpapers.  When you give it the `http` url, it's trying to load that exact url as an image (this is usually for webcams/security cams).  Without an api, there's really no way I'll be able to add support for these, sorry.

**Comment by Taylorben159** [comment]
Thank you for the quick response and explanation for what was going on.  I
thought that 'might' be the issue, but I wanted to double check.
