### ISSUE TITLE
Error: cannot find module 'flicker-sdk'

### ISSUE THREAD

**Issue by usafle** [kolbyjack/MMM-Wallpaper#65]
I did a git-pull to grab the newest update.  Now my M.M. will not start as the above error message halts the loading of my MagicMirror instance.

**Comment by kolbyjack** [comment]
I added a dependency on flickr-sdk for the updated flickr api support.  You'll need to run `npm install` in the MMM-Wallpaper directory to install it

**Comment by usafle** [comment]
Thanks.  That appears to have fixed the issue.  Also, thanks for the quick response!
