### ISSUE TITLE
Flickr-api source not working

### ISSUE THREAD

**Issue by Taylorben159** [kolbyjack/MMM-Wallpaper#66]
Good evening,
  I have tried to get my personal photostream to show up as my picture source in your module and I cannot get it to work.  I have no errors in my config.js that break MagicMirror and keep it from loading, so I think I just have my source information not input correct.  Can you take a look at my config to see if it is obvious to you?

 {
    module: "MMM-Wallpaper",
    position: "middle_center",
    config: { // See "Configuration options" for more information.
      source: "flickr-api:2d5b6<redacted for privacy>157bf2f6c403c:photos/soulreavers",
      shuffle: true,
      slideInterval: 60 * 1000 // Change slides every minute
    }
  },

I have tried formatting the source line several ways and sometimes I will get the stock flickr photos, but they are only 10 pixels tall and all the way across the screen.  I have tried putting my API key where flickr-api is and I still just get a black screen in the middle of my MM.  Do I need to put "photos/soulreavers" on a lower line or just change how it is attached to the API key?  Flickr has a secret code as part of their API process.  Do I need to incorporate it into my key somehow?  Finally, I still have my MagicMirror "app" for Flickr (needed to get my API key) set as Private.  Do I just need to make it Public and suddenly everything will work fine?  Thank you for your help with this.

**Comment by kolbyjack** [comment]
I'm going to guess that part of the issue is setting your position to `"middle-center"`, if you want it to cover the whole screen, you'll want `"fullscreen_below"`.  The secret code that goes with your api key is only necessary for uploading/managing items, so you don't need it in the config, as the module only reads data.  Try something like this:

```
{
  module: "MMM-Wallpaper",
  position: "fullscreen_below",
  config: {
    source: "flickr-api:photos/soulreavers",
    flickrApiKey: "2d5b6157bf2f6c403c",
    shuffle: true,
    slideInterval: 60000
  }
}
```

**Comment by kolbyjack** [comment]
Also, if that really is your api key/secret, and not just a placeholder, you should revoke it and generate a new one, as it should never be shared with anyone.

**Comment by Taylorben159** [comment]
I had cut out two thirds of my API key when I started my question, but must
have done an edit with a copy and paste that put the full API back in.  The
position and correct formatting for my API key fixed it.  Thank you for
your help and I will be generating a new API key now.

**Comment by Taylorben159** [comment]
Turns out I can still put the location as "middle_center" and have a useable picture if I then set "fillRegion" to false.
