### ISSUE TITLE
shuffle not really working

### ISSUE THREAD

**Issue by Taylorben159** [kolbyjack/MMM-Wallpaper#67]
I have my flickr source set up to my personal flickr account, set to pull from 400 images (although I only currently have about 100 pictures in the gallery), and is set to shuffle randomly between those pictures.  Everything seemed to be working great for a while, but I have noticed that it really only shuffles between about 25 pictures.  I have attached  my configuration for you to look through and see if you see anything obvious.  Thank you for your help.

module: "MMM-Wallpaper",
position: "middle_center",
config: {
        source: "flickr-api:redacted",
        flickrApiKey: "redacted",
        fillRegion: false,
        width: "auto",
        height: "891px",
        shuffle: true,
        maximumEntries: 400,
        slideInterval: 60 * 1000

**Comment by kolbyjack** [comment]
I wasn't requesting a specific page size when making flickr api requests, and I was always limiting the return to at most 60 photos.  Give the latest a try and see if it works for you.  Note that the module has to make an api request for each photo to get the high resolution urls, so keep an eye on your api key usage.
