### ISSUE TITLE
Set Images to Center_Middle of Screen

### ISSUE THREAD

**Issue by mbosselle** [kolbyjack/MMM-Wallpaper#71]
Hey wondering how I would go about centring images in the middle of the screen? Currently, I'm restricting the images to the width of the screen. The images then justify to the top of the layout. My config is below

```
{
			module: "MMM-Wallpaper",
			position: "fullscreen_below",
			config: {
				source: "Local:/home/pi/Pictures/Magic Mirror Album",
				slideInterval: 1 * 60 * 1000,
				fadeEdges: true,
				fillRegion: false,
				width: 1080,
				height: "auto"
			}
		}
```

Thanks kindly for your time

**Comment by kolbyjack** [comment]
Instead of seeing the width and height manually, try setting "size": "contain"

**Comment by mbosselle** [comment]
Yep, that solved my issue. 

Thank you very much
