### ISSUE TITLE
filter option

### ISSUE THREAD

**Issue by BlouZbee** [kolbyjack/MMM-Wallpaper#79]
Is the filter option broken? im adding it to config.js. error unexpected token filter. thank you.

**Comment by kolbyjack** [comment]
That probably means you're missing a comma somewhere.  Can you post your MMM-Wallpaper config section?

**Comment by BlouZbee** [comment]
ugg, the "//Change slides every minute" in the example config was throwing me off visually and I missed the comma.  You are correct. Thank you.
