### ISSUE TITLE
maximumEntries needed for local source continual shuffle?

### ISSUE THREAD

**Issue by apiontek** [kolbyjack/MMM-Wallpaper#81]
Hi - thanks for this module! A question:

I am just using the `local` source for a directory of 13k images (so far! I'll likely be adding).

Does the `maximumEntries` with shuffle mean only n images are loaded and shuffled through, and no more entries are ever loaded for a MM instance that just sits running all day? Or will it keep loading new images? In other words, if I really want it to randomly shuffle through all 13k images over a long period of time, do I need to set `maximumEntries` to something like maybe 15000?

**Comment by kolbyjack** [comment]
With `shuffle` enabled on a `local` source, the module will read all of the images in the given directory, then shuffle, and then will cycle through the first `maximumEntries` images until the next `updateInterval`, at which point, it will re-shuffle and a new set of photos will be chosen.

**Comment by apiontek** [comment]
Oh that is perfect, thank you for that clarification!
