### ISSUE TITLE
Add brief caption indicating filename for local images

### ISSUE THREAD

**Issue by apiontek** [kolbyjack/MMM-Wallpaper#82]
I would like to see the filename for the image displayed, when local source is used.

I was able to add it by adding a line to `images.push` in node_helper.js, so it looks like:

```js
images.push({
  url: `${urlPath}${dirent}`,
  caption: `File: "${dirent}"`,
});
```

I can do a pull request if desired.

**Comment by kolbyjack** [comment]
Went ahead and committed with just `caption: dirent`, is that satisfactory?

**Comment by apiontek** [comment]
Yes, that's excellent, thank you. I do tend to do more than is necessary!

**Comment by RomainLG** [comment]
@kolbyjack

Hi there, would it be possible to have the caption only be the filename?

And not as is, the full path.

i.e. Display for example "mypicture" instead of "/home/user/media/mypicture.png"
