### ISSUE TITLE
fillRegion not observing dimensions set with height and width

### ISSUE THREAD

**Issue by asc11111** [kolbyjack/MMM-Wallpaper#85]
I am running MM in portrait mode and I want to put an image in the top bar and have a calendar view below in the bottom bar. I want to restrict the size of the image at the top to a maximum of 608 so I have the following in my config.js file

```
		{
			  // small image above calendar
			  module: 'MMM-Wallpaper',
			  position: 'top_bar',
			  config: {
				source: "<local source>",
				caption: false,
				slideInterval: 100000,
				crossfade: false,
				maximumEntries: 1000,
				filter:"grayscale(0) brightness(1)",
				fadeEdges: true,
				size: "contain",
				fillRegion: false,
				height: 608,
				width: "auto",
			  }
		},
```

No matter what size I put in for height and width it doesn't make a difference to what is displayed.

**Comment by kolbyjack** [comment]
I believe you need to include the units for css, try `height: "608px"`

**Comment by asc11111** [comment]
Thank you - that worked!
