### ISSUE TITLE
orientation label ignored on Reddit

### ISSUE THREAD

**Issue by hweigel** [kolbyjack/MMM-Wallpaper#9]
Using the MM in portrait mode. When setting orientation to either "vertical" or "auto", the module still pulls and displays landscape images from the subreddit. Tested with multiple channels, e.g. r/EarthPorn, r/MostBeautiful. Please advise.

**Comment by kolbyjack** [comment]
Is your expectation that it would skip landscape oriented images from reddit?  "vertical" and "auto" currently only mean something to the bing source, since it provides 1920x1080 and 1080x1920 versions of each background.

**Comment by hweigel** [comment]
Yeah, that kinda was what I expected. I'll stick with bing until I'll grow the stones to fork your module.
Maybe you could add that detail regarding orientation only working for bing to the Readme.md.

Last but not least, a) great module and b) thx for getting back to me so quickly.
