### ISSUE TITLE
Incompatibility with MMM-ModuleScheduler?

### ISSUE THREAD

**Issue by cal3d** [kolbyjack/MMM-Wallpaper#92]
I've been trying to use MMM-ModuleScheduler to hide and show background images on a schedule.  The hide operation works, however MMM-Wallpaper does not re-enable showing of images when the show command is sent.  I've checked the debug logs for MMM-ModuleScheduler to confirm that the command is being sent, however all that is displayed is a black screen. 

Is it expected that this should work? 

Thanks

**Comment by kolbyjack** [comment]
I know users have used the user presence messages to show and hide the module, but it looks like MMM-ModuleScheduler is doing the showing and hiding itself, so if there's an issue, I would check with that module's author.
