### ISSUE TITLE
caption set to false does not remove file name from bottom right corner

### ISSUE THREAD

**Issue by bma-diy** [kolbyjack/MMM-Wallpaper#95]
{
			module: "MMM-Wallpaper",
			position: "fullscreen_below",
			config: {
				source: ["local:/home/pi/Pictures"],
				crossfade: false,
				//filter: "grayscale(0.5) brightness(0.4)",
				filter: "grayscale(0.25) brightness(0.5)",
				size: "cover",
				caption: "false",
				slideInterval: 3 * 60 * 1000
				//orientation: "vertical",
				//maximumEntries: 10,
			}

**Comment by kolbyjack** [comment]
javascript is really weird, `"false"` is a string that is "truthy", while `false` is a boolean value that is false.  Remove the quotes and the caption should disappear.

**Comment by bma-diy** [comment]
Thank you!! I knew I was missing something basic.
